package com.alxarafe.app.domain.topology.valueobject;

import java.util.Objects;

/**
 * Value Object representing a generated location code.
 *
 * The code is generated by the LocationCodeGenerator domain service
 * according to the Zone's NamingPolicy.
 */
public record LocationCode(String value) {

    public LocationCode {
        Objects.requireNonNull(value, "LocationCode cannot be null.");
        if (value.isBlank()) {
            throw new IllegalArgumentException("LocationCode cannot be empty.");
        }
        if (value.length() > 50) {
            throw new IllegalArgumentException(
                    "LocationCode must not exceed 50 characters. Got: " + value);
        }
    }

    @Override
    public String toString() {
        return value;
    }
}
