<?php

declare(strict_types=1);

namespace Alxarafe\App\Domain\Topology\ValueObject;

use InvalidArgumentException;

/**
 * Value Object representing a generated location code.
 *
 * The code is generated by the LocationCodeGenerator domain service
 * according to the Zone's NamingPolicy.
 */
final readonly class LocationCode
{
    public function __construct(private string $value)
    {
        if ($value === '') {
            throw new InvalidArgumentException('LocationCode cannot be empty.');
        }

        if (strlen($value) > 50) {
            throw new InvalidArgumentException(
                'LocationCode must not exceed 50 characters. Got: ' . $value
            );
        }
    }

    public function value(): string
    {
        return $this->value;
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
